<?php

/**
 * Implements hook_theme()
 * @return mixed
 */
function events_theme($existing, $type, $theme, $path)
{
  return [
    // Theme Hook For content() in Test Controller.
    'test_custom_hook' =>
      [
        'template' => 'events',
        'variables' =>
          [
            'variable1' => 'Yet another default text.',
            'variable2' => 0,
            'variable3' => [0, 0, 0],
          ]
      ],
    // Theme Hook For index() in Event Controller.
    'event_custom_hook' =>
      [
        'template' => 'description',
        'variables1' => 'Empty Template',
      ],
  ];
}
